import type { Ride, User } from './types';

export const MOCK_USER: User = {
  id: 'u0',
  name: 'Алексей Морозов',
  telegram: 'alexmorozov',
};

export const MOCK_RIDES: Ride[] = [
  {
    id: 'r1',
    driverId: 'u1',
    driverName: 'Софья Чен',
    from: 'Центральная библиотека',
    to: 'Северный кампус',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    time: '08:15',
    telegram: 'sophiechen',
    price: 3.5,
    distanceKm: 6.2,
    isPeak: true,
    createdAt: Date.now() - 100000,
  },
  {
    id: 'r2',
    driverId: 'u2',
    driverName: 'Дмитрий Парк',
    from: 'Общежитие «Риверсайд»',
    to: 'Инженерный корпус',
    days: ['Mon', 'Wed', 'Fri'],
    time: '09:00',
    telegram: 'dmitrypark',
    price: 2.8,
    distanceKm: 4.5,
    isPeak: true,
    createdAt: Date.now() - 90000,
  },
  {
    id: 'r3',
    driverId: 'u3',
    driverName: 'Мария Гарсия',
    from: 'Западные квартиры',
    to: 'Студенческий союз',
    days: ['Tue', 'Thu'],
    time: '10:30',
    telegram: 'mariagarcia',
    price: 2.0,
    distanceKm: 3.1,
    isPeak: false,
    createdAt: Date.now() - 80000,
  },
  {
    id: 'r4',
    driverId: 'u4',
    driverName: 'Давид Ким',
    from: 'Центр города',
    to: 'Южный кампус',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    time: '07:45',
    telegram: 'davidkim',
    price: 4.2,
    distanceKm: 7.8,
    isPeak: true,
    createdAt: Date.now() - 70000,
  },
  {
    id: 'r5',
    driverId: 'u5',
    driverName: 'Эмма Уилсон',
    from: 'Кафе «Холм»',
    to: 'Научный блок',
    days: ['Wed', 'Fri'],
    time: '14:00',
    telegram: 'emmawilson',
    price: 1.5,
    distanceKm: 2.0,
    isPeak: false,
    createdAt: Date.now() - 60000,
  },
  {
    id: 'r6',
    driverId: 'u6',
    driverName: 'Лиам Джонсон',
    from: 'Восточные ворота',
    to: 'Библиотека',
    days: ['Sat'],
    time: '11:00',
    telegram: 'liamjohnson',
    price: 2.5,
    distanceKm: 3.8,
    isPeak: false,
    createdAt: Date.now() - 50000,
  },
  {
    id: 'r7',
    driverId: 'u7',
    driverName: 'Оливия Браун',
    from: 'Университетская деревня',
    to: 'Медицинский факультет',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    time: '08:30',
    telegram: 'oliviabrown',
    price: 3.0,
    distanceKm: 5.5,
    isPeak: true,
    createdAt: Date.now() - 40000,
  },
  {
    id: 'r8',
    driverId: 'u8',
    driverName: 'Ной Дэвис',
    from: 'Спортивный комплекс',
    to: 'Главная площадь',
    days: ['Tue', 'Thu', 'Sat'],
    time: '16:30',
    telegram: 'noahdavis',
    price: 2.2,
    distanceKm: 3.4,
    isPeak: false,
    createdAt: Date.now() - 30000,
  },
];
